//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkinciEl.DF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracSatis
    {
        public int AracSatisID { get; set; }
        public System.DateTime SatisTarihi { get; set; }
        public float SatinAlinanFiyat { get; set; }
        public int AracID { get; set; }
        public int KullanıcıID { get; set; }
        public int SatisTipiID { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual SatisTipi SatisTipi { get; set; }
    }
}
