//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkinciEl.DF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertizMerkez
    {
        public int ExpertizMerkezID { get; set; }
        public string ExpertizMerkezAdi { get; set; }
        public string ExpertizMerkezAdresi { get; set; }
        public string ExpertizMerkezTelefonu { get; set; }
        public string ExpertizMerkezMaili { get; set; }
    }
}
