//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkinciEl.DF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IhaleFiyat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IhaleFiyat()
        {
            this.IhaleFiyatKullanici = new HashSet<IhaleFiyatKullanici>();
            this.TeklifVerdigimArac = new HashSet<TeklifVerdigimArac>();
        }
    
        public int IhaleFiyatID { get; set; }
        public float Fiyat { get; set; }
        public int SiraNo { get; set; }
        public int KullaniciID { get; set; }
        public int IhaleID { get; set; }
    
        public virtual Ihale Ihale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IhaleFiyatKullanici> IhaleFiyatKullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeklifVerdigimArac> TeklifVerdigimArac { get; set; }
    }
}
