//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkinciEl.DF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.AldigimArac = new HashSet<AldigimArac>();
            this.Arac = new HashSet<Arac>();
            this.AracSatis = new HashSet<AracSatis>();
            this.Favori = new HashSet<Favori>();
            this.Ihale = new HashSet<Ihale>();
            this.IhaleFiyatKullanici = new HashSet<IhaleFiyatKullanici>();
            this.Mesaj = new HashSet<Mesaj>();
            this.SattigimArac = new HashSet<SattigimArac>();
            this.Statu = new HashSet<Statu>();
            this.TeklifVerdigimArac = new HashSet<TeklifVerdigimArac>();
        }
    
        public int KullaniciID { get; set; }
        public string KullaniciAdi { get; set; }
        public string AdVeSoyad { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public bool KullaniciAktifmi { get; set; }
        public string Sifre { get; set; }
        public int ToplamIhaleAracSayisi { get; set; }
        public bool KullaniciOnaylimi { get; set; }
        public bool KVKKTiklimi { get; set; }
        public int RolID { get; set; }
        public int PaketID { get; set; }
        public int SirketBilgisiID { get; set; }
        public Nullable<bool> KurumsalMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AldigimArac> AldigimArac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arac> Arac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AracSatis> AracSatis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favori> Favori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ihale> Ihale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IhaleFiyatKullanici> IhaleFiyatKullanici { get; set; }
        public virtual Paket Paket { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual SirketBilgisi SirketBilgisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mesaj> Mesaj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SattigimArac> SattigimArac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Statu> Statu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeklifVerdigimArac> TeklifVerdigimArac { get; set; }
    }
}
