//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkinciEl.DF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IkinciElAracEntities : DbContext
    {
        public IkinciElAracEntities()
            : base("name=IkinciElAracEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AldigimArac> AldigimArac { get; set; }
        public virtual DbSet<Arac> Arac { get; set; }
        public virtual DbSet<AracDonanim> AracDonanim { get; set; }
        public virtual DbSet<AracMarka> AracMarka { get; set; }
        public virtual DbSet<AracModel> AracModel { get; set; }
        public virtual DbSet<AracSatis> AracSatis { get; set; }
        public virtual DbSet<Donanim> Donanim { get; set; }
        public virtual DbSet<ExpertizMerkez> ExpertizMerkez { get; set; }
        public virtual DbSet<Favori> Favori { get; set; }
        public virtual DbSet<FirmaTuru> FirmaTuru { get; set; }
        public virtual DbSet<Gorsel> Gorsel { get; set; }
        public virtual DbSet<GovdeTipi> GovdeTipi { get; set; }
        public virtual DbSet<Ihale> Ihale { get; set; }
        public virtual DbSet<IhaleFiyat> IhaleFiyat { get; set; }
        public virtual DbSet<IhaleFiyatKullanici> IhaleFiyatKullanici { get; set; }
        public virtual DbSet<IhaleStatu> IhaleStatu { get; set; }
        public virtual DbSet<Ilanbilgisi> Ilanbilgisi { get; set; }
        public virtual DbSet<Komisyon> Komisyon { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Mesaj> Mesaj { get; set; }
        public virtual DbSet<NoterUcret> NoterUcret { get; set; }
        public virtual DbSet<Paket> Paket { get; set; }
        public virtual DbSet<Parca> Parca { get; set; }
        public virtual DbSet<Renk> Renk { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<SatisTipi> SatisTipi { get; set; }
        public virtual DbSet<SattigimArac> SattigimArac { get; set; }
        public virtual DbSet<SirketBilgisi> SirketBilgisi { get; set; }
        public virtual DbSet<Statu> Statu { get; set; }
        public virtual DbSet<StatuTipi> StatuTipi { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TeklifVerdigimArac> TeklifVerdigimArac { get; set; }
        public virtual DbSet<TramerBilgisi> TramerBilgisi { get; set; }
        public virtual DbSet<TramerBilgisiDurum> TramerBilgisiDurum { get; set; }
        public virtual DbSet<VitesTipi> VitesTipi { get; set; }
        public virtual DbSet<YakitTipi> YakitTipi { get; set; }
    }
}
