//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkinciEl.DF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TramerBilgisi
    {
        public int TramerBilgisiID { get; set; }
        public int TramerBilgisiDurumID { get; set; }
        public int ParcaID { get; set; }
        public int AracID { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual Parca Parca { get; set; }
        public virtual TramerBilgisiDurum TramerBilgisiDurum { get; set; }
    }
}
